server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
  zipkin:
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

eureka:
   healthcheck:
     enabled: true
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
